import type { SpaceDocument } from "@/types";

export const MOCK_DOCUMENTS: SpaceDocument[] = [
  {
    id: "1",
    title: "James Webb Deep Field Spectroscopic Analysis",
    description: "Comprehensive spectral data from JWST's first deep field observations, covering redshift z=10-15 galaxies.",
    category: "Astronomy",
    contributor: "Dr. Elena Vasquez",
    fileSize: 45_200_000,
    fileType: "PDF",
    uploadDate: "2024-11-15",
    tags: ["JWST", "Deep Field", "Spectroscopy", "High-z Galaxies"],
    downloads: 2847,
    country: "USA",
  },
  {
    id: "2",
    title: "Artemis III Lunar Surface Mission Plan",
    description: "Detailed operational plan for the third Artemis crewed lunar landing, including EVA schedules and sample collection sites.",
    category: "Missions",
    contributor: "NASA Artemis Team",
    fileSize: 12_800_000,
    fileType: "PDF",
    uploadDate: "2024-10-22",
    tags: ["Artemis", "Moon", "Crewed Mission", "EVA"],
    downloads: 5621,
    country: "USA",
  },
  {
    id: "3",
    title: "Sentinel-6 Sea Level Rise Dataset 2024",
    description: "Global ocean altimetry measurements showing 3.7mm/year sea level rise trends from ESA Sentinel-6 satellite.",
    category: "Earth Observation",
    contributor: "ESA Climate Team",
    fileSize: 2_300_000_000,
    fileType: "CSV",
    uploadDate: "2024-12-01",
    tags: ["Sea Level", "Climate", "Sentinel-6", "Altimetry"],
    downloads: 1203,
    country: "Germany",
  },
  {
    id: "4",
    title: "Exoplanet Atmosphere Characterization — TOI-700d",
    description: "Transmission spectroscopy revealing water vapor and CO2 signatures in the atmosphere of super-Earth TOI-700d.",
    category: "Deep Space",
    contributor: "Prof. Kenji Tanaka",
    fileSize: 8_700_000,
    fileType: "PDF",
    uploadDate: "2024-09-14",
    tags: ["Exoplanet", "Atmosphere", "Biosignatures", "TOI-700d"],
    downloads: 3982,
    country: "Japan",
  },
  {
    id: "5",
    title: "Starlink Gen2 Orbital Constellation Data",
    description: "Complete TLE dataset and collision avoidance statistics for Starlink Generation 2 satellite constellation.",
    category: "Satellites",
    contributor: "SpaceTrack Consortium",
    fileSize: 980_000,
    fileType: "JSON",
    uploadDate: "2024-11-30",
    tags: ["Starlink", "LEO", "TLE", "Constellation"],
    downloads: 7451,
    country: "USA",
  },
  {
    id: "6",
    title: "Dark Matter Distribution in Bullet Cluster",
    description: "Chandra X-ray + gravitational lensing reconstruction showing dark matter spatial distribution in 1E 0657-558.",
    category: "Research",
    contributor: "Dr. Amara Osei",
    fileSize: 156_000_000,
    fileType: "FITS",
    uploadDate: "2024-08-07",
    tags: ["Dark Matter", "Bullet Cluster", "X-ray", "Lensing"],
    downloads: 892,
    country: "Ghana",
  },
  {
    id: "7",
    title: "Perseverance Rover Jezero Crater Geology Map",
    description: "High-resolution geological survey of Jezero Crater floor, delta fan, and ancient river channel structures.",
    category: "Missions",
    contributor: "Mars 2020 Science Team",
    fileSize: 340_000_000,
    fileType: "PNG",
    uploadDate: "2024-07-19",
    tags: ["Mars", "Perseverance", "Geology", "Jezero"],
    downloads: 4320,
    country: "USA",
  },
  {
    id: "8",
    title: "Gravitational Wave Event GW230529 Data",
    description: "LIGO-Virgo-KAGRA detection data for neutron star-black hole merger, including waveform and sky localization.",
    category: "Astronomy",
    contributor: "LIGO Scientific Collaboration",
    fileSize: 67_000_000,
    fileType: "PDF",
    uploadDate: "2024-06-11",
    tags: ["Gravitational Waves", "LIGO", "Neutron Star", "Black Hole"],
    downloads: 6103,
    country: "International",
  },
  {
    id: "9",
    title: "Indian ISRO Aditya-L1 Solar Wind Dataset",
    description: "First-light solar wind plasma measurements from India's Aditya-L1 spacecraft at the L1 Lagrange point.",
    category: "Research",
    contributor: "ISRO Space Science Division",
    fileSize: 23_400_000,
    fileType: "CSV",
    uploadDate: "2024-05-28",
    tags: ["Solar Wind", "Aditya-L1", "ISRO", "L1 Point"],
    downloads: 1876,
    country: "India",
  },
];
